# application server configuration
- hosts: application
  become: yes
  roles:
    - role: alp
      tags: alp
    - role: pt-query-digest
      tags: pt-query-digest
    - role: redis
      tags: redis
